import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, query, orderBy, limit, serverTimestamp, updateDoc, doc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const $=id=>document.getElementById(id); let auth=null,db=null,itemData=[],allBills=[],currentBillId=null,editTarget=null;
try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);$("firebaseState").textContent="Connected";}catch(e){console.error(e);$("firebaseState").textContent="Configuration error";}
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
function nextNo(){let n=+(localStorage.getItem("ms_bill_no")||1000)+1;localStorage.setItem("ms_bill_no",n);return n}
const money=n=>Number(n||0).toFixed(2); const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function num(v){return Number(String(v??"").replace(/,/g,""))||0}
function calc(){const total=itemData.reduce((s,x)=>s+num(x.qty)*num(x.rate),0);const paid=Math.max(0,num($("paidAmount").value));const due=Math.max(0,total-paid);$("editorTotal").textContent=money(total);$("dueAmount").value=money(due);$("summaryTotal").textContent=money(total);$("summaryPaid").textContent=money(paid);$("summaryDue").textContent=money(due);return{total,paid,due}}
function data(){const c=calc();return{billNo:$("billNo").value.trim(),date:$("billDate").value,customerName:$("customerName").value.trim(),phone:$("phone").value.trim(),mobile:$("mobile").value.trim(),address:$("address").value.trim(),items:itemData.map(x=>({description:x.description||"",qty:num(x.qty),rate:num(x.rate)})),total:c.total,paidAmount:c.paid,dueAmount:c.due,serviceType:$("serviceType").value,paymentStatus:$("paymentStatus").value,paymentMethod:$("paymentMethod").value,referenceNo:$("referenceNo").value.trim()}}
function renderItems(){const w=$("items");w.innerHTML="";itemData.forEach((x,i)=>{const r=document.createElement("div");r.className="item-row";r.innerHTML=`<div>${i+1}</div><input class="desc" value="${esc(x.description)}" placeholder="Service / particulars"><input class="qty" type="text" inputmode="numeric" value="${x.qty||1}"><input class="rate" type="text" inputmode="decimal" value="${x.rate||0}"><input class="amount" value="₹ ${money(num(x.qty)*num(x.rate))}" readonly><button class="remove" type="button">×</button>`;const desc=r.querySelector(".desc"),qty=r.querySelector(".qty"),rate=r.querySelector(".rate"),amount=r.querySelector(".amount");desc.oninput=e=>{x.description=e.target.value;sync()};qty.oninput=e=>{e.target.value=e.target.value.replace(/[^0-9]/g,"");x.qty=num(e.target.value);amount.value="₹ "+money(x.qty*x.rate);sync()};rate.oninput=e=>{e.target.value=e.target.value.replace(/[^0-9.]/g,"").replace(/(\..*)\./g,"$1");x.rate=num(e.target.value);amount.value="₹ "+money(x.qty*x.rate);sync()};r.querySelector(".remove").onclick=()=>{itemData.splice(i,1);if(!itemData.length)itemData.push({description:"",qty:1,rate:0});renderItems();sync()};w.appendChild(r)})}
function sync(){const d=data();$("headBillNo").textContent=d.billNo||"—";$("pBillNo").textContent=d.billNo||"—";$("pDate").textContent=d.date?new Date(d.date+"T00:00:00").toLocaleDateString("en-GB"):"";$("pName").textContent=d.customerName;$("pMobile").textContent=d.phone||d.mobile;$("pPhoneTop").textContent=d.phone||d.mobile;$("pAddress").textContent=d.address;$("pTotal").textContent=money(d.total);$("pPayment").textContent=d.paymentMethod+(d.paymentStatus?" • "+d.paymentStatus:"");const t=$("printItems");t.innerHTML="";for(let i=0;i<Math.max(7,d.items.length);i++){const x=d.items[i],tr=document.createElement("tr");tr.innerHTML=`<td>${x?i+1:""}</td><td>${x?esc(x.description):""}</td><td>${x?x.qty:""}</td><td>${x?money(x.rate):""}</td><td>${x?money(x.qty*x.rate):""}</td>`;t.appendChild(tr)}}
function fill(d={}){currentBillId=d.id||null;$("billNo").value=d.billNo||nextNo();$("billDate").value=d.date||today();$("customerName").value=d.customerName||"";$("phone").value=d.phone||d.mobile||"";$("mobile").value=d.mobile||"";$("address").value=d.address||"";$("serviceType").value=d.serviceType||"";$("paymentStatus").value=d.paymentStatus||"Paid";$("paymentMethod").value=d.paymentMethod||"Cash";$("referenceNo").value=d.referenceNo||"";$("paidAmount").value=d.paidAmount??0;itemData=d.items?.length?d.items.map(x=>({...x})): [{description:"",qty:1,rate:0}];$("saveStatus").textContent="";renderItems();sync()}
function toast(s,big=false){const t=$("toast");t.textContent=s;t.classList.add("show");if(big)t.classList.add("big");setTimeout(()=>t.classList.remove("show","big"),3200)}
async function save(){const d=data();if(!d.customerName)return alert("Customer Name is required.");if(!auth?.currentUser)return alert("Please login first.");$("saveStatus").textContent="Saving…";try{if(currentBillId){await updateDoc(doc(db,"bills",currentBillId),{...d,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});toast("✓ BILL UPDATED SUCCESSFULLY",true)}else{const ref=await addDoc(collection(db,"bills"),{...d,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});currentBillId=ref.id;toast("✓ BILL SAVED SUCCESSFULLY",true)}$("saveStatus").textContent="Saved ✓";await loadBills()}catch(e){console.error(e);$("saveStatus").textContent="Save failed";alert("Firebase save failed: "+e.message)}}
async function loadBills(){try{const snap=await getDocs(query(collection(db,"bills"),orderBy("createdAt","desc"),limit(200)));allBills=snap.docs.map(x=>({id:x.id,...x.data()}));renderHistory();renderCustomers()}catch(e){console.error(e);$("historyList").innerHTML=`<div class="card error-card">Could not load bills. Check Firestore rules.<br><small>${esc(e.message)}</small></div>`}}
function newBillFrom(x=null){fill({billNo:nextNo(),date:today(),customerName:x?.customerName||"",phone:x?.phone||x?.mobile||"",mobile:x?.mobile||"",address:x?.address||"",items:[{description:"",qty:1,rate:0}]});showTab("billing");setTimeout(()=>{$("customerName").focus();window.scrollTo({top:0,behavior:"smooth"})},80)}
function renderHistory(){const q=$("historySearch").value.toLowerCase().trim();const a=allBills.filter(x=>`${x.billNo} ${x.customerName} ${x.phone} ${x.mobile}`.toLowerCase().includes(q));$("historyList").innerHTML=a.length?a.map(x=>`<div class="history-card"><div><b>Bill #${esc(x.billNo)}</b><strong>${esc(x.customerName||"Unnamed")}</strong><div class="meta">${esc(x.date||"")} • ${esc(x.phone||x.mobile||"No phone")} • ₹ ${money(x.total)}</div></div><div class="card-actions"><button data-open="${x.id}">Open</button><button data-edit="${x.id}">Edit</button><button data-new="${x.id}">New Bill</button><button data-wa="${x.id}">WhatsApp</button></div></div>`).join(""):"<div class='card empty'>No matching bills found.</div>";document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{const x=allBills.find(v=>v.id===b.dataset.open);if(x){fill(x);showTab("billing")}});document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const x=allBills.find(v=>v.id===b.dataset.edit);if(x)openEditModal(x)});document.querySelectorAll("[data-new]").forEach(b=>b.onclick=()=>{const x=allBills.find(v=>v.id===b.dataset.new);newBillFrom(x)});document.querySelectorAll("[data-wa]").forEach(b=>b.onclick=()=>whatsapp(allBills.find(v=>v.id===b.dataset.wa)))}
function renderCustomers(){const q=$("customerSearch").value.toLowerCase().trim(),m=new Map();allBills.forEach(x=>{const k=(x.phone||x.mobile||x.customerName||"").toLowerCase();if(!m.has(k))m.set(k,{...x,count:1,total:num(x.total)});else{m.get(k).count++;m.get(k).total+=num(x.total)}});const a=[...m.values()].filter(x=>`${x.customerName} ${x.phone} ${x.mobile}`.toLowerCase().includes(q));$("customerList").innerHTML=a.length?a.map(x=>`<div class="customer-card"><div><b>${esc(x.customerName||"Unknown")}</b><div class="meta">${esc(x.phone||x.mobile||"No phone")} • ${x.count} bill(s) • ₹ ${money(x.total)}</div></div><div class="card-actions"><button data-cust-new="${esc(x.id)}">New Bill</button><button data-cust-edit="${esc(x.id)}">Edit</button></div></div>`).join(""):"<div class='card empty'>No customers found.</div>";document.querySelectorAll("[data-cust-new]").forEach(b=>b.onclick=()=>newBillFrom(allBills.find(v=>v.id===b.dataset.custNew)));document.querySelectorAll("[data-cust-edit]").forEach(b=>b.onclick=()=>{const x=allBills.find(v=>v.id===b.dataset.custEdit);if(x)openEditModal(x)})}
function openEditModal(x){editTarget=x;$("editName").value=x.customerName||"";$("editPhone").value=x.phone||x.mobile||"";$("editModal").classList.remove("hidden");$("editName").focus()}function closeEditModal(){editTarget=null;$("editModal").classList.add("hidden")}
async function saveCustomerEdit(){if(!editTarget)return;const name=$("editName").value.trim(),phone=$("editPhone").value.trim();if(!name)return alert("Customer Name cannot be empty.");try{await updateDoc(doc(db,"bills",editTarget.id),{customerName:name,phone,mobile:phone,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});closeEditModal();toast("✓ CUSTOMER DETAILS UPDATED",true);await loadBills()}catch(e){alert("Update failed: "+e.message)}}
function showTab(tab){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));["billing","history","customers"].forEach(x=>$(x+"Tab").classList.toggle("hidden",x!==tab));if(tab==="billing")setTimeout(()=>window.scrollTo({top:0,behavior:"smooth"}),30)}
function whatsapp(d=null){d=d||data();if(!d.customerName)return alert("Enter customer name first.");let p=(d.phone||d.mobile||"").replace(/\D/g,"");if(p.length===10)p="91"+p;const text=encodeURIComponent(`Hello ${d.customerName},\n\nMa Shamsundari Online Services\nBill No: ${d.billNo}\nDate: ${d.date}\nTotal: ₹ ${money(d.total)}\nPaid: ₹ ${money(d.paidAmount)}\nDue: ₹ ${money(d.dueAmount)}\n\nThank you for choosing us.`);window.open(`https://wa.me/${p}?text=${text}`,"_blank")}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$("addItemBtn").onclick=()=>{itemData.push({description:"",qty:1,rate:0});renderItems();sync()};$("newBillBtn").onclick=()=>newBillFrom();$("saveBtn").onclick=save;$("printBtn").onclick=()=>window.print();$("shareBtn").onclick=()=>whatsapp();$("clearBtn").onclick=()=>newBillFrom();$("historySearch").oninput=renderHistory;$("refreshHistory").onclick=loadBills;$("historyNewBill").onclick=()=>newBillFrom();$("customerSearch").oninput=renderCustomers;$("refreshCustomers").onclick=loadBills;["billNo","billDate","customerName","phone","mobile","address","serviceType","paymentStatus","paymentMethod","referenceNo","paidAmount"].forEach(id=>$(id).addEventListener("input",sync));$("loginBtn").onclick=async()=>{if(!auth)return;const email=$("loginEmail").value.trim(),pass=$("loginPassword").value;if(!email||!pass)return $("loginMsg").textContent="Enter email and password.";$("loginMsg").textContent="Signing in…";try{await signInWithEmailAndPassword(auth,email,pass);$("loginMsg").textContent=""}catch(e){$("loginMsg").textContent=e.code+" — "+e.message.replace("Firebase: ","")}};$("logoutBtn").onclick=()=>signOut(auth);$("closeEdit").onclick=closeEditModal;$("cancelEdit").onclick=closeEditModal;$("saveEdit").onclick=saveCustomerEdit;$("editModal").onclick=e=>{if(e.target.id==="editModal")closeEditModal()};
onAuthStateChanged(auth,u=>{if(u){$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");fill({billNo:nextNo(),date:today(),items:[{description:"",qty:1,rate:0}]});loadBills()}else{$("loginScreen").classList.remove("hidden");$("app").classList.add("hidden")}});
